# Generated by Django 4.0.1 on 2022-01-16 06:39

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default=accounts.models.get_rand_token, max_length=255, unique=True),
        ),
    ]
